### ISSUE TITLE
Add ability to send tips specific currency ammount

### ISSUE THREAD

**Issue by sironitomas** [blocktrail/slack-tipbot#2]
For example:

@tipbot send 25 ARS to @pedro for Coffee
@tipbot I want to receive 3 USD from @bob

**Comment by sironitomas** [comment]
@rubensayshi is this hard to do? I'll try doing it myself when I have more time...

**Comment by rubensayshi** [comment]
hey @sironitomas sorry somehow I missed your ticket ... 

it's actually not that hard I guess...  
however it would require us having the correct bitcoin price for the requested currency!

atm our API only has EUR / USD / GBP: https://api.blocktrail.com/v1/btc/price?api_key=MY_APIKEY  
which is based on actual markets, for Peso's we'd have to convert between USD and atm I don't really have a great source for currency conversion and it's not really 'correct', but acceptable I guess.

I guess supporting EUR / USD / GBP would be a start at least ... I'll try to free up some time 2morrow !

**Comment by sironitomas** [comment]
That is great! I'll check if there's a good source for the ARS rate (since the official one is invalid). I know Copay guys are doing that right. @ChangeTip, give @rubensayshi a coffee.

**Comment by changetip** [comment]
Hi @rubensayshi, @sironitomas sent you a Bitcoin tip worth a coffee (5,245 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/882423)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by rubensayshi** [comment]
seems to be working fine, I'll merge the pull request on monday and deploy to our hosted slackbots :)

**Comment by sironitomas** [comment]
Nice! I talked to the Copay guys and they told me they use currency rates from the Bitpay public API. So for ARS, it's just a matter of using this (https://bitpay.com/api/rates/ARS).

Thanks again!

**Comment by rubensayshi** [comment]
hey @sironitomas, I added the usage of the bitpay rates and just merged it and deployed it, should be working! 

```
rubensayshi [6:12 PM]: @tipbot: send @boaz 1 ARS
tipbot [6:12 PM]: OK! I'll send @boaz 1.00 ARS (0.00025396 BTC at 3937.72 ARS / BTC)
```

**Comment by sironitomas** [comment]
Fantastic work @rubensayshi! I'll test how this works tomorrow :)
